export {
  SonarrDecodeError,
  SonarrDeleteConfirmationRequiredError,
  SonarrEnvMissingError,
  SonarrError,
  SonarrHttpError,
  SonarrNotFoundError,
  SonarrUnreachableError,
  decodeError,
  deleteConfirmationRequired,
  envFix,
  envMissing,
  httpError,
  notFound,
  unreachable,
} from './errors.js'
export type { SonarrErrorCode } from './errors.js'
export { SonarrApiLive } from './http.js'
export {
  addSeries,
  calendar,
  config,
  defaultCalendarDays,
  defaultLimit,
  exists,
  firstTvdbId,
  history,
  missing,
  queue,
  removeSeries,
  search,
  status,
} from './operations.js'
export { SonarrApi, SonarrConfig, SonarrConfigLive } from './services.js'
export type {
  AddSeriesApiOptions,
  AddSeriesOptions,
  AddSeriesResult,
  CalendarOptions,
  CalendarResult,
  ConfigSummary,
  EpisodeRecord,
  ExistsResult,
  HistoryRecord,
  LimitOptions,
  ListResult,
  QualityProfile,
  QueueRecord,
  RemoveSeriesOptions,
  RemoveSeriesResult,
  RootFolder,
  SearchResult,
  SeriesLookupResult,
  SeriesRecord,
  SeriesStatistics,
  SonarrConfigValue,
  SystemStatus,
} from './model.js'
