export {
  JellyfinConfirmationRequiredError,
  JellyfinDecodeError,
  JellyfinEnvMissingError,
  JellyfinError,
  JellyfinHttpError,
  JellyfinNotFoundError,
  JellyfinUnreachableError,
  confirmationRequired,
  decodeError,
  envFix,
  envMissing,
  httpError,
  notFound,
  unreachable,
} from './errors.js'
export type { JellyfinErrorCode } from './errors.js'
export { JellyfinApiLive } from './http.js'
export {
  ItemRecordSchema,
  JellyfinConfigValueSchema,
  LibraryRecordSchema,
  LibraryStatsSchema,
  LimitOptionsSchema,
  ListResultSchema,
  NowPlayingRecordSchema,
  RunTaskResultSchema,
  ScheduledTaskRecordSchema,
  SearchOptionsSchema,
  SessionRecordSchema,
  SystemStatusSchema,
  UserRecordSchema,
} from './model.js'
export type {
  ItemRecord,
  JellyfinConfigValue,
  LibraryRecord,
  LibraryStats,
  LimitOptions,
  ListResult,
  NowPlayingRecord,
  RunTaskResult,
  ScheduledTaskRecord,
  SearchOptions,
  SessionRecord,
  SystemStatus,
  UserRecord,
} from './model.js'
export {
  defaultLimit,
  itemSearch,
  libraries,
  libraryStats,
  nowPlaying,
  recentlyAdded,
  runTask,
  scheduledTasks,
  sessions,
  status,
  users,
} from './operations.js'
export { JellyfinApi, JellyfinConfig, JellyfinConfigLive } from './services.js'
