export {
  RadarrCollectionConfirmationRequiredError,
  RadarrDecodeError,
  RadarrDeleteConfirmationRequiredError,
  RadarrEnvMissingError,
  RadarrError,
  RadarrHttpError,
  RadarrNotFoundError,
  RadarrUnreachableError,
  collectionConfirmationRequired,
  decodeError,
  deleteConfirmationRequired,
  envFix,
  envMissing,
  httpError,
  notFound,
  unreachable,
} from './errors.js'
export type { RadarrErrorCode } from './errors.js'
export { RadarrApiLive } from './http.js'
export {
  AddCollectionMovieActionSchema,
  AddCollectionMovieResultSchema,
  AddCollectionOptionsSchema,
  AddCollectionResultSchema,
  AddMovieApiOptionsSchema,
  AddMovieOptionsSchema,
  AddMovieResultSchema,
  CalendarOptionsSchema,
  CalendarResultSchema,
  CollectionInfoResultSchema,
  CollectionRecordSchema,
  ConfigSummarySchema,
  ExistsResultSchema,
  HistoryRecordSchema,
  LimitOptionsSchema,
  ListResultSchema,
  MovieCollectionSummarySchema,
  MovieLookupResultSchema,
  MovieRecordSchema,
  MovieReleaseRecordSchema,
  QualityProfileSchema,
  QueueRecordSchema,
  RadarrConfigValueSchema,
  RemoveMovieOptionsSchema,
  RemoveMovieResultSchema,
  RootFolderSchema,
  SearchResultSchema,
  SystemStatusSchema,
} from './model.js'
export type {
  AddCollectionMovieAction,
  AddCollectionMovieResult,
  AddCollectionOptions,
  AddCollectionResult,
  AddMovieApiOptions,
  AddMovieOptions,
  AddMovieResult,
  CalendarOptions,
  CalendarResult,
  CollectionInfoResult,
  CollectionRecord,
  ConfigSummary,
  ExistsResult,
  HistoryRecord,
  LimitOptions,
  ListResult,
  MovieCollectionSummary,
  MovieLookupResult,
  MovieRecord,
  MovieReleaseRecord,
  QualityProfile,
  QueueRecord,
  RadarrConfigValue,
  RemoveMovieOptions,
  RemoveMovieResult,
  RootFolder,
  SearchResult,
  SystemStatus,
} from './model.js'
export {
  addCollection,
  addMovie,
  calendar,
  collectionInfo,
  config,
  defaultAddCollectionResultLimit,
  defaultCalendarDays,
  defaultLimit,
  exists,
  firstTmdbId,
  history,
  missing,
  queue,
  removeMovie,
  search,
  status,
} from './operations.js'
export { RadarrApi, RadarrConfig, RadarrConfigLive } from './services.js'
